### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by coldfix** [nathan-hoad/gbulb#1]
Hey,

I'm planning to make use of asyncio+PyGI in one of my applications, which is why I've been interested in gbulb for some time. I did a brief test and was happy to see that your fork seemed to work (whereas the gbulb package on bitbucket produced some errors).

I saw that you have already registered this package on PyPI. Can you make releases and upload them to PyPI whenever there is any relevant change, so it will be easier to add this package as a dependency?

Best regards,
Thomas

**Comment by nathan-hoad** [comment]
Yes! Definitely. My plan is to get 0.2 onto PyPI once I have test coverage up - there's some testing remaining around the default signal handling, then it should be good to go. My plan is to have this out by the end of this week.

I'll update and close this issue when that's become a reality :)

**Comment by coldfix** [comment]
Thanks, that sounds great:) - and take your time!

**Comment by nathan-hoad** [comment]
Okay, a quite sizeable bug was found and fixed this week, and test coverage is pretty good now, so I decided to bite the bullet and uploaded 0.2 to PyPI!
