### ISSUE TITLE
run_until_complete() stopped by loop.stop()

### ISSUE THREAD

**Issue by Jajcus** [nathan-hoad/gbulb#10]
In `asyncio loop.stop()` is supposed to terminate `loop.run_forever()` only. The gbulb implementation would also stop `loop.run_until_complete()` making it incompatible.

For my code it causes unexpected exception and error log:

    RuntimeError: Event loop stopped before Future completed.
    ERROR:asyncio:Task was destroyed but it is pending!

**Comment by nathan-hoad** [comment]
What you're saying is not true, `loop.stop()` is supposed to terminate the loop regardless of how it was started. As shown below, `loop.stop()` will terminate `run_until_complete()` as well as `loop.run_forever()` in both asyncio and gbulb with the error you're describing:

    nathan@laptop ~ $ cat asyncio-stop.py
    import asyncio

    async def task():
        loop.call_later(1, loop.stop)
        await asyncio.sleep(5000)

    loop = asyncio.get_event_loop()
    print(loop)
    loop.run_until_complete(task())

    nathan@laptop ~ $ cat gbulb-stop.py
    import asyncio
    import gbulb
    gbulb.install()

    async def task():
        loop.call_later(1, loop.stop)
        await asyncio.sleep(5000)

    loop = asyncio.get_event_loop()
    print(loop)
    loop.run_until_complete(task())

    nathan@laptop ~ $ python asyncio-stop.py
    <_UnixSelectorEventLoop running=False closed=False debug=False>
    Traceback (most recent call last):
      File "asyncio-stop.py", line 9, in <module>
        loop.run_until_complete(task())
      File "/usr/lib/python3.5/asyncio/base_events.py", line 385, in run_until_complete
        raise RuntimeError('Event loop stopped before Future completed.')
    RuntimeError: Event loop stopped before Future completed.

    nathan@laptop ~ $ python gbulb-stop.py
    <GLibEventLoop running=False closed=False debug=False>
    Traceback (most recent call last):
      File "gbulb-stop.py", line 11, in <module>
        loop.run_until_complete(task())
      File "/home/nathan/projects/gbulb/gbulb/glib_events.py", line 134, in run_until_complete
        raise RuntimeError('Event loop stopped before Future completed.')
    RuntimeError: Event loop stopped before Future completed.

**Comment by Jajcus** [comment]
Which Python version do you have?

**Comment by Jajcus** [comment]
Ok, you are right. It seems difference of my code behaviour was caused by something else. The asyncio documentation is not clear enough, which assured me in my confusion.

I am sorry for bothering you then.

**Comment by nathan-hoad** [comment]
That's all good! I agree, there are many places in the asyncio documentation that are not clear enough. It's very frustrating.

**Comment by astronouth7303** [comment]
"provisional"
