### ISSUE TITLE
Test routine fails while trying to install

### ISSUE THREAD

**Issue by hell-g** [nathan-hoad/gbulb#12]
I am trying to install gbulb on Arch Linux using the AUR package and the test session fails. Could it be because of the new Python 3.6?
Thanks!

> $ makepkg
> ==> Making package: python-gbulb 0.4-1 (Tue Jan 10 12:33:17 CET 2017)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Found 0.4.tar.gz
> ==> Validating source files with sha256sums...
>     0.4.tar.gz ... Passed
> ==> Extracting sources...
>   -> Extracting 0.4.tar.gz with bsdtar
> ==> Removing existing $pkgdir/ directory...
> ==> Starting check()...
> ==================================== test session starts ====================================
> platform linux -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
> rootdir: /home/rhaelg/Packages/python-gbulb/src/gbulb-0.4, inifile: 
> collected 45 items 
> 
> tests/test_glib_events.py .................................F
> tests/test_gtk.py ...
> tests/test_utils.py ........
> 
> ========================================= FAILURES ==========================================
> _____________________________________ test_subprocesses _____________________________________
> 
> glib_loop = <GLibEventLoop running=False closed=False debug=False>
> 
>     def test_subprocesses(glib_loop):
>         import asyncio
>         import subprocess
>     
>         # needed to ensure events.get_child_watcher() returns the right object
>         import gbulb
>         gbulb.install()
>     
>         @asyncio.coroutine
>         def coro():
>             proc = yield from asyncio.create_subprocess_exec(
>                 'cat', stdout=subprocess.PIPE, stdin=subprocess.PIPE,
>                 stderr=subprocess.PIPE, loop=glib_loop)
>     
>             proc.stdin.write(b'hey\n')
>             yield from proc.stdin.drain()
>     
>             proc.stdin.close()
>     
>             out = yield from proc.stdout.read()
>             assert out == b'hey\n'
>     
> >       glib_loop.run_until_complete(coro())
> 
> tests/test_glib_events.py:451: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> gbulb/glib_events.py:136: in run_until_complete
>     return future.result()
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> 
>     @asyncio.coroutine
>     def coro():
>         proc = yield from asyncio.create_subprocess_exec(
>             'cat', stdout=subprocess.PIPE, stdin=subprocess.PIPE,
>             stderr=subprocess.PIPE, loop=glib_loop)
>     
>         proc.stdin.write(b'hey\n')
>         yield from proc.stdin.drain()
>     
>         proc.stdin.close()
>     
>         out = yield from proc.stdout.read()
> >       assert out == b'hey\n'
> E       assert b'' == b'hey\n'
> E         Right contains more items, first extra item: 104
> E         Use -v to get the full diff
> 
> tests/test_glib_events.py:449: AssertionError
> ============================ 1 failed, 44 passed in 0.68 seconds ============================
> ==> ERROR: A failure occurred in check().
>     Aborting...
>

**Comment by nathan-hoad** [comment]
Hello,

It is indeed because of 3.6! I've got a fix that I will test and push out within the next 8 hours or so.

Thanks for reporting this!

Nathan.

**Comment by nathan-hoad** [comment]
Alright, as noted by my commit, this is good to go in the 0.5 release. Thanks again for reporting this!
