### ISSUE TITLE
Test hangs on python 3.5.3

### ISSUE THREAD

**Issue by BrechtDeVlieger** [nathan-hoad/gbulb#15]
On Debian Stretch with python3.5.3rc1: the unit test tests/test_glib_events.py::TestGLibHandle::test_attachment_order seems to hang for some reason. Pressing Ctrl+C makes the test pass. All the other tests pass without a problem.
Output: (To see ^C event)
...
tests/test_glib_events.py::TestGLibEventLoopPolicy::test_new_event_loop_application PASSED
tests/test_glib_events.py::TestGLibHandle::test_attachment_order ^CPASSED
tests/test_glib_events.py::TestBaseGLibEventLoop::test_add_signal_handler PASSED
...

**Comment by nathan-hoad** [comment]
Interesting! I'll take a look at this one and get back to you in the next 24 hours.

**Comment by nathan-hoad** [comment]
I have a fix for this that I'm going to put out later today - simple test fix only, no code changes.
