### ISSUE TITLE
Using another event loop at the same time 

### ISSUE THREAD

**Issue by stuaxo** [nathan-hoad/gbulb#18]
Is that OK with this ?

I was going to have another loop that I use for sending network messages.

**Comment by astronouth7303** [comment]
Isn't the point of async that you don't generally need multiple loops?

**Comment by nathan-hoad** [comment]
Yes, astronouth7303 is correct. Like Tim Peters said about metaclasses, "If you wonder whether you need them, you don’t (the people who actually need them know with certainty that they need them, and don’t need an explanation about why)".

**Comment by stuaxo** [comment]
Cheers, I guess I just need to run different executors in the same loop to achieve what I want.

I have some network tasks, that end up blocking my gobject + gstreamer based video player, which I could probably put into a separate process, but a separate executor seems like the way to go.

I'm on a raspberry pi3, so have a few 4 cores, but individually, they aren't very fast.


This is my first program using aio, so I'm still in the asking-silly-questions-phase :)

**Comment by astronouth7303** [comment]
Either your network stuff needs to be rewritten to be async (network was the impetus of asyncio), or you need to use [`.run_in_executor()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.run_in_executor)
