### ISSUE TITLE
Hail from gpotato!

### ISSUE THREAD

**Issue by astronouth7303** [nathan-hoad/gbulb#2]
Hey, I tried this awhile ago under [gpotato](https://github.com/astronouth7303/gpotato), and found the effort to update the test suite to be... substantial. We should probably unify our efforts.
- Did you get control of the gbulb name? If not, did you want to take over as gpotato?
- How is the test stuff going? Should I work on merging my travis work into your work?

In general, I think everyone involved would like to get this done so we can stop yak shaving and get back to whatever project we were trying to do.

**Comment by nathan-hoad** [comment]
Hello! Yes I'd be very interested in unifying our efforts.

I've gotten control of the gbulb name - I spoke with the original maintainer and he's given me write access to PyPI, so I can push releases there when they're ready. I had plans to push a 0.2 release there this weekend but the time ran away from me.

Test wise, I'm up to 77% coverage - the only two things remaining are tests for the default signal handling (with a fix for when that handling is installed), and for watching child processes. I don't have them running on Travis though, which I would definitely welcome!

I do also need to finish writing up some examples for this version of gbulb - generally it can be used the same as the old version, but the API is a lot cleaner now (in my opinion).

**Comment by astronouth7303** [comment]
I'll have to see if I can port the travis stuff over.

Isn't the API just asyncio?

> (with a fix for when that handling is installed)

I noticed there seemed to be a gap in that.

**Comment by nathan-hoad** [comment]
Yes, just asyncio! I was unclear, my apologies. The API is asyncio, but the way you set up the event loop is slightly different to how it was in the old version of gbulb - you use `gbulb.install(gtk=True)` for a Gtk event loop policy, for example. You can still use the old way for the most part, but in my eyes this is a bit cleaner. 

There's also no such thing as an application event loop policy, they're all rolled into two event loops (Gtk and GLib) that handle applications if you provide them.

**Comment by astronouth7303** [comment]
Hmm. [Travis](https://travis-ci.org/astronouth7303/gbulb) is being weird for both gpotato and gbulb. Odd build problems.

(For the record, you have to build pygobject manually because the system version is only for the version of python installed from apt: 3.2.)

**Comment by nathan-hoad** [comment]
Alright, I've finally gotten around to taking a look at this, and I've got http://drone.getoffmalawn.com running now, testing against 3.4, 3.5 and 3.6. pygobject was painful!
