### ISSUE TITLE
ImportError on Windows

### ISSUE THREAD

**Issue by gbtami** [nathan-hoad/gbulb#23]
C:\gbulb>python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gbulb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\gbulb\gbulb\__init__.py", line 1, in <module>
    from .glib_events import *
  File "C:\gbulb\gbulb\glib_events.py", line 21, in <module>
    import fcntl
ImportError: No module named 'fcntl'
>

**Comment by nathan-hoad** [comment]
Whoops, I forgot about that! I've pushed a fix for this now. A heads up though, interacting with standard IO of subprocesses doesn't look like it works quite right in Windows yet, so you might want to avoid that for the time being.

**Comment by gbtami** [comment]
Thx! Just in case I filed this problem in issue #24
