### ISSUE TITLE
ImportError: cannot import module 'sslproto'

### ISSUE THREAD

**Issue by gbtami** [nathan-hoad/gbulb#27]
Debian 8 (Jessie) was shipped with Python 3.4.2 and asyncio has sslproto.py from 3.4.3 only!

**Comment by nathan-hoad** [comment]
What version of gbulb are you running?

**Comment by gbtami** [comment]
Latest from git.

**Comment by nathan-hoad** [comment]
Ah, I hadn't noticed that Debian 8 came out in 2015 - as of the next release Python 3.4 and below won't be supported, because we need to use the new asyncio.sslproto module.
