### ISSUE TITLE
Submit a wheel package to PyPI

### ISSUE THREAD

**Issue by freakboy3742** [nathan-hoad/gbulb#28]
gbulb is currently submitted to PyPI as a source package. When you try to install gbulb from PyPI using pip 9, the installation process attempts to invoke bdist_wheel, which may not be installed. This means anyone using gbulb must list `wheel` as a install requirement, even if they don't intend to package any code - and as soon as gbulb is installed, `wheel` can be uninstalled.

This could be avoided if a wheel was uploaded to PyPI:
```
pip install wheel twine
python setup.py bdist_wheel sdist
twine upload dist/*
```

However, this can only be done by the PyPI package owner.

**Comment by nathan-hoad** [comment]
Good catch! I've submitted a wheel for the most recent release, 0.5.3, and I'll make sure to do it for future releases. Cheers Russell!
