### ISSUE TITLE
Support for network connections?

### ISSUE THREAD

**Issue by lordi** [nathan-hoad/gbulb#3]
Maybe I'm missing something, but I can't get gbulb to work with network connections like this:

    from gi.repository import Gtk
    import asyncio
    import gbulb
    
    @asyncio.coroutine
    def open_connection():
        print("connecting")
        yield from asyncio.open_connection('www.google.com', 80)
        print("connected")

    def main():
        gbulb.install(gtk=True)
        loop = gbulb.get_event_loop()

        asyncio.async(open_connection())
        loop.run_forever()
    
    if __name__ == '__main__':
        main()

"connected" is never printed. Similar behaviour with ``aiofiles``, ``asyncio.start_server``, etc.

**Comment by nathan-hoad** [comment]
Interesting! I definitely see this behaviour, so I will take a look when I get a chance - definitely not sometime this week as I'm quite busy with work, I'm sorry, but hopefully on the weekend.

Thank you for testing it and bringing it to my attention!

**Comment by nathan-hoad** [comment]
@lordi Could you try again with the latest revision? I believe the issue should be fixed now.

**Comment by lordi** [comment]
I would, but there is no new revision pushed to this repository

**Comment by nathan-hoad** [comment]
@lordi My bad! I've pushed my changes now.

**Comment by lordi** [comment]
Yep, now it appears to work, thanks!
