### ISSUE TITLE
Thanks for gbulb

### ISSUE THREAD

**Issue by stuaxo** [nathan-hoad/gbulb#46]
Just saw your messages about not having time to work on this any more and just wanted to say thanks for making it.

When I needed async Gtka couple of years ago gbulb came in very handy.

Wish I had the time to take it over myself.

**Comment by nathan-hoad** [comment]
Thanks Stuart! I'm glad the work was appreciated, I'm sad I can't work on it anymore. Hopefully someone finds the time!

**Comment by stuaxo** [comment]
It's certainly hard to find time, I hope that in the future there is a way to fund work that needs to adequately fund changes in smaller open source projects.
