### ISSUE TITLE
StreamWriter.write() only writes part of data

### ISSUE THREAD

**Issue by sth** [nathan-hoad/gbulb#5]
I have a subprocess and write data to its stdin. This works up to a certain amount of data, but stalls for larger amounts. The initial data is written, but after ~500KB it stops and nothing happens anymore.

```python
import gbulb; gbulb.install()
import asyncio, subprocess

# 1000 rather long lines of input data
indata = ('x' * 10000 + '\n') * 1000

def run():
   proc = yield from asyncio.create_subprocess_exec('sed', '-n', '=', stdin=subprocess.PIPE)
   proc.stdin.write(indata.encode('ascii'))
   proc.stdin.close()
   yield from proc.wait()

asyncio.get_event_loop().run_until_complete(asyncio.async(run()))
```

Here the `sed` command prints a number for each input line. It would be expected to count up to 1000, for the 1000 input lines. For me it only counts up to 40-60 and then hangs.

It looks like
- When [`proc.stdin.write()`][1] is called, some data is written to the pipe. The remainder is stored in `self._buffer` for later writing.
- [`_write_ready()`][2] is called. It writes some more data (but not all of it). Since it didn't write all data, it doesn't remove itself from the event loop.
- `_write_ready()` is never called again.

Source of the problem seems to be that the write handle [doesn't have its `repeat` parameter set][3] and therefore [removes itself][4] from the event loop after it was executed for the first time. So no repeated `_write_ready()` calls happen and the remaining data is never written.

Setting `repeat=True` when the write handle is [created][3] seems to fix the problem, though I don't know if it causes other complications.

[1]: https://github.com/python/cpython/blob/master/Lib/asyncio/unix_events.py#L483
[2]: https://github.com/python/cpython/blob/master/Lib/asyncio/unix_events.py#L516
[3]: https://github.com/nathan-hoad/gbulb/blob/master/gbulb/glib_events.py#L236
[4]: https://github.com/nathan-hoad/gbulb/blob/master/gbulb/glib_events.py#L100

**Comment by nathan-hoad** [comment]
Hello, thanks for the awesome bug report! I can reproduce this, and setting `repeat=True` does fix your issue, but does also introduce a complication, frustratingly.

If you try running this code:

```import asyncio
import gbulb


def main():
    gbulb.install()
    loop = gbulb.get_event_loop()

    loop.run_until_complete(asyncio.open_connection('www.google.com', 80))

    print('done')

if __name__ == '__main__':
    main()
```

You'll see tracebacks being repeatedly spewed to the terminal, which are caused by setting `repeat=True`. So from your bug report, it seems it needs to be `repeat=True` with some conditions on when to actually stop repeating, I guess. I'll look into this further, but if you have any ideas, I'd be glad to hear them! :)

**Comment by nathan-hoad** [comment]
Awesome find! Took a bit to debug that one. Both of the example scripts in here now run successfully for me - if you could try your StreamWriter code again to confirm it works, that would be good.

**Comment by sth** [comment]
Thanks for the quick fix! I updated my code to the newest revision and it works great. I don't see any problems anymore.
