### ISSUE TITLE
Porting from Glib.idle_add

### ISSUE THREAD

**Issue by stuaxo** [nathan-hoad/gbulb#8]
Hi,
   I'm looking at porting a gstreamer app to gbulb.

Before porting I use ```GLib.idle_add(callback_func)``` when I use gbulb coroutines, will they be basically equivalent ?

**Comment by nathan-hoad** [comment]
You want to use the call_soon method, documented here: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.call_soon

You cannot use coroutines with any of the call_* methods however.
